### ISSUE TITLE
Slightly inefficient.

### ISSUE THREAD

**Issue by ioquatix** [noahgibbs/fiber_basic_benchmarks#1]
https://github.com/noahgibbs/fiber_basic_benchmarks/blob/b6615f4a29c70e3a6dfa01476a8a149452886f6d/pipe/remastered_fiber_test.rb#L93

So, this code was kept simple at the expense of being slightly inefficient. Because it will invoke the reactor even if the read/write would succeed.

Because what you are doing is a micro-benchmark, it could be influenced by this in a not-so-insignificant way.

**Comment by noahgibbs** [comment]
That makes sense. I'll look into attempting a nonblocking read first before invoking the reactor. And I think the process and thread versions don't have this same difficulty, which makes it especially worth fixing.

**Comment by ioquatix** [comment]
I'm just collecting results for you locally, but Ruby 2.0 is definitely not on par with Ruby 2.6 or 2.7 - it's way slower.

One thing to remember is that I/O operations (including `IO.select`) are syscalls and will blow any improvement to `Fiber.yield` out of the water. So, because this is a micro benchmark you need to try to isolate what it is you are comparing pretty carefully. Source code and numbers coming your way shortly.

**Comment by ioquatix** [comment]
One other point, is you may sometimes want to look at running with GC disabled.

GC can be a big overhead on threads and fibers and it basically only introduces instability in the results. You will see a regression in 2.7.0-preview1 which was caused by the incremental GC being switched on. Previously, my understanding, is that it was not working correctly. There is not much public discussion but there is a summary here https://bugs.ruby-lang.org/issues/16009

The work I did in 2.7.0 past preview1 improved performance enough to be back on par with 2.6 and faster in some cases.

**Comment by ioquatix** [comment]
https://github.com/socketry/async/tree/master/benchmark/rubies - code + results from my desktop, seem pretty reproducible to me. See if you get the same spread/changes.

**Comment by noahgibbs** [comment]
On both my Mac locally and EC2 linux testing with a large dedicated instance, your version seems a bit slower than mine. Which seems, frankly, odd. However, I've only tested on 2.0.0-p0 through 2.6.5 - maybe it's faster on 2.7? I'll try that next. Certainly the difference for Ruby 2.0 is very large (around 50% slower) while on 2.6 it's nearly as fast. So 2.7 may be the answer.

I might also have messed up importing yours somehow - you can see the file I tested with as williams_fiber_test.rb next to baseline fiber_test.rb here: https://github.com/noahgibbs/fiber_basic_benchmarks/tree/master/benchmarks

There are a couple of changes, but they're to the command line parameters and the file output, just to hook it into the test harness. I didn't intend to make any substantive changes.

**Comment by ioquatix** [comment]
I feel like it should be faster on all Rubies compared to the original version... but `IO.select` is not the best.

Can we find out specifically what part is 50% slower?

**Comment by noahgibbs** [comment]
I could run StackProf on both versions and compare. I'll do that for the earliest Ruby I can (probably 2.1, looking at StackProf's docs) and 2.6, plus probably 2.7 since I need to time that anyway.

**Comment by ioquatix** [comment]
Oh, there is a known regression with using `read_noblock`.  It's notoriously slow in older rubies because it totally fucks up the global method cache because the exception is recreated every time it's thrown. It's a huge mess. It was kind of cleared up in later rubies but the issue still kind of remains. Which is why `exception: false` is preferable and actually the only sane choice.

See https://bugs.ruby-lang.org/issues/5138 and specifically https://bugs.ruby-lang.org/issues/5138#note-28 which honestly, given how bad the perf was, doesn't do the issue justice.

**Comment by noahgibbs** [comment]
Ah, okay. I saw a check for Ruby version being >= 2.3 that I thought fixed that, but looking at the code, probably not.

Interesting! I noticed that yours was slower in very old Rubies, and that makes sense with read_nonblock, and I noticed it was a bit slower for Ruby 2.6, but I didn't look carefully at all the data in between. For Ruby 2.3 and 2.4, your version is noticeably faster.

**Comment by noahgibbs** [comment]
Here we go... I'll give median values -- probably more representative than mean, though I have both. And I'll give results with just message times, no process overhead, though that doesn't seem to make much difference. I'm giving the numbers with 10 workers here, because overall that seems fastest - though in recent Ruby the 100-worker numbers have basically caught up with the 10-worker. Measurements are in total seconds to process 100,000 messages with that many workers.

'Vanilla' fiber test:
2.0.0-p0: 15.1
2.1.10: 17.4
2.2.10: 23.9
2.3.8: 23.4
2.4.5: 22.1
2.5.3: 16.9
2.6.5: 12.6 (note: std dev 0.30)

Your fiber test:
2.0.0-p0: 29.7
2.1.10: 26.6
2.2.10: 30.5
2.3.8: 20.8
2.4.5: 20.4
2.5.3: 17.4
2.6.5: 14.8 (note: std dev 0.26)

(Also, how did I see 50% slower? Those numbers are more like 100% slower for 2.0.0. I was probably looking at a different number of workers.)

I specifically noted the std dev on the final numbers because it's a bit odd that your benchmark dropped relative to the normal one, so I checked to make sure it wasn't just a high-variance (noisy) measurement. Doesn't seem to be.

So yeah, the 2.7 numbers may be educational here.

**Comment by ioquatix** [comment]
The other thing to bear in mind is that the original benchmark is actually kind of wrong.

Calling wait readable followed by read is not completely non-blocking.

The updated implementation has to do all the buffering in user space, but that's needed because we have to use `read_nonblock` vs `read`. That probably accounts for some of the slow down too. `read` implements a tight loop in C, but it's blocking.

One thing to be aware of is that blocking IO will always be lower overhead than non-blocking. Non-blocking I/O naturally has a bit more overhead. But because it's non-blocking, overall latency should be reduced.

**Comment by noahgibbs** [comment]
Yeah. At some point I may do a latency (rather than throughput/bulk-work) benchmark, and at that point there will need to be a pretty significant number of changes. These benchmarks aren't optimised for that case at all, basically.

**Comment by ioquatix** [comment]
I guess what I'm saying, is that it would be possible for the original implementation to deadlock, even thought it doesn't happen in practice.

The latter implementation is more close to how async actually works right now. But ideally it can be more efficient by hooking directly into Ruby.

**Comment by ioquatix** [comment]
Just to clarify, you are measuring not just the overheads of threads vs fibers, but also blocking I/O vs non-blocking I/O. You are blending two different measurements in a single benchmark which probably makes it harder to interpret the results.

If you wanted to compare a pure thread context switch vs fiber context switch, you can do that by message passing.

See all `vm2_fiber_*` benchmarks here (most I wrote): https://github.com/ruby/ruby/tree/master/benchmark

Specifically: https://github.com/ruby/ruby/blob/master/benchmark/fiber_chain.yml

Some people would argue that micro-bechmarks are a waste of time, but for me, I need to get a tight distribution for a specific chunk of functionality. Tricky to judge whether the benchmark you put together is objective enough or reflects a real world scenario.

**Comment by noahgibbs** [comment]
I think that checking reading/writing across pipes between threads, processes and fibers is a sufficiently common setup that it's worth testing. All else aside, this looks a fair bit like how you set up an application server or similar worker/master server for large or heterogenous workloads on a network server.

**Comment by ioquatix** [comment]
Sure, but then you should also use `read_nonblock` in threads, to normalise that overhead.

**Comment by noahgibbs** [comment]
At the moment I have regular blocking read in both thread and fiber benchmarks available. But yes, it could make sense to also add a nonblocking thread test to compare to the nonblocking fiber test.

**Comment by ioquatix** [comment]
It is true that blocking I/O makes more sense for threads. They have higher overhead context switching but lower overhead I/O. Blocking I/O will always beat non-blocking I/O, especially if it's in a tight loop ala `sendfile`.

**Comment by noahgibbs** [comment]
I feel like in this test, the nonblocking version isn't shown well. As such, it seems reasonable to me to close this bug - basically, because properly measuring this inefficiency would first require writing a different test measuring different things. Does that make sense to you?

**Comment by ioquatix** [comment]
I think it’s okay as long as the results are clearly explained. But yeah super tricky.
